Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.define "server" do |server|
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.50.20"
        server.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.memory = "1024"
        end
    end

    config.vm.define "db" do |db|
        db.vm.hostname = "db"
        db.vm.network "private_network", ip: "192.168.50.21"
        db.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.memory = "1024"
        end
    end
end